language: android
sudo: false
jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools

    - build-tools-21.1.1

    - android-21

    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    - sys-img-armeabi-v7a-android-21

script:
  - cordova run android