language: android
sudo: false
jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools

    - build-tools-21.1.1

    - android-21

    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    - sys-img-armeabi-v7a-android-21

before_script:
   - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
   - emulator -avd test -no-skin -no-audio -no-window &
   - adb wait-for-device
   - adb shell input keyevent 82 &

script:
  - ./platforms/android/gradlew connectedCheck